steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    id: update staging server
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        set -x && \
        gcloud compute ssh instance-1 --zone=europe-west9-a --command='/bin/sh /home/xdarkus/tm-server/pull.sh