steps:

  # Connect to the VM using SSH client
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'xdarkus77@tm-server'
      - '--project=tm-server-krz'
      - '--zone=europe-west9-a'
      - '--command=cd tm-server && git pull && cd compose && sudo docker compose up -d'