steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export SSH_KEY=$(gcloud secrets versions access latest --secret="xdarkus77-vm-ssh-key")

  # Connect to the VM using SSH client
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - '-c'
      - |
        mkdir -p ~/root/.ssh && \\
        gcloud secrets versions access latest --secret=xdarkus77-vm-ssh-key > ~/root/.ssh/id_rsa && \\
        chmod 600 ~/root/.ssh/id_rsa && \\
        set -x && \\
        gcloud compute ssh instance-1 --ssh-key-file=~/root/.ssh/id_rsa --zone=europe-west9-a