steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export SSH=$(gcloud secrets versions access latest --secret="xdarkus77-vm-ssh-key")

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'xdarkus77@instance-1'
      - '--project=tm-server-krz'
      - '--zone=europe-west9-a'
      - '--ssh-key-file=${_SSH}'
      - '--command=cd tm-server && git pull && cd ./compose && docker-compose up -d --build'