steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export SSH_KEY=$(gcloud secrets versions access latest --secret="xdarkus77-vm-ssh-key")

  # Connect to the VM using SSH client
  - name: 'gcr.io/cloud-builders/ssh'
    args:
      - '-i'
      - '${_SSH_KEY}'
      - '-o'
      - 'StrictHostKeyChecking=no'
      - '-o'
      - 'UserKnownHostsFile=/dev/null'
      - 'xdarkus77@instance-1'
      - 'cd tm-server && git pull && cd ./compose && docker-compose up -d --build'