steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p ~/root/.ssh &&
        gcloud secrets versions access latest --secret=cloud-build-ssh-key > ~/root/.ssh/id_rsa &&
        chmod 600 ~/root/.ssh/id_rsa &&
        gcloud secrets versions access latest --secret=cloud-build-ssh-key-pub > ~/root/.ssh/id_rsa.pub &&
        chmod 600 ~/root/.ssh/id_rsa.pub &&
        gcloud compute ssh server-name --ssh-key-file=~/root/.ssh/id_rsa --zone=europe-west9-a --command='git pull && cd ./compose && docker-compose up -d'