steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'instance-1'
      - '--project=tm-server-krz'
      - '--zone=europe-west9-a'
      - '--ssh-key-file=$$SSH-KEY'
      - '--command=cd tm-server && git pull'
    secretEnv: ['SSH-KEY']
availableSecrets:
  secretManager:
  - versionName: projects/873476583868/secrets/cloud-build-ssh-key/versions/1
    env: 'SSH-KEY'