version: '3.7'

services:
  database:
    image: mariadb:latest
    container_name: database
    restart: on-failure
    volumes:
      - database-volume:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pyplanet
      MYSQL_USER: pyplanet
      MYSQL_PASSWORD: pyplanet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute="SHOW DATABASES;"
      interval: 60s
      timeout: 2s
      retries: 1
      start_period: 15s
    networks:
      - server-network

  server:
    image: tm-server
    container_name: server
    depends_on:
      - database
    build: 
      context: .
      dockerfile: ./server.Dockerfile
    environment:
      SERVER_TITLE: "Trackmania"
      SERVER_NAME: "KRZ Training"
      TRACKLIST: "royal.xml"
    ports:
      - 2351:2351/udp
      - 2351:2351/tcp
      - 3451:3451/tcp
      - 3451:3451/udp
    expose:
      - 5006
    volumes:
      - ./dedicated_cfg.xml:/home/server/tm_server/UserData/Config/dedicated_cfg.xml:z
      - ./maps:/home/server/tm_server/UserData/Maps:z
    networks:
      - server-network

  pyplanet:
    container_name: pyplanet
    image: tm-pyplanet
    build: 
      context: .
      dockerfile: ./pyplanet.Dockerfile
    
    restart: on-failure
    depends_on:
      - database
      - server
    volumes:
      - ./pyplanet/settings:/home/server/pyplanet/settings:Z
      - ./maps:/home/server/pyplanet/UserData/Maps:z
    networks:
      - server-network

networks:
  server-network:
    driver: bridge

volumes:
  database-volume:
    driver: local